#! /bin/sh

cd /var/www/app

if [ "$WEB_TYPE" = "admin" ]
then
	cp .env.admin .env
fi

if [ "$WEB_TYPE" = "user" ]
then
	php artisan migrate --force && \
	php artisan db:audit-triggers && \
	php artisan optimize:clear
fi

php artisan optimize && \
chown -R apache bootstrap/cache storage
php-fpm83 && \
httpd -DFOREGROUND 

