#! /bin/sh
# run_serve

usage() {
	echo "Usage: $0 [-br]"
	echo
	exit 1
}

push_assets() {
	npm run build
	rsync -avz -I --delete public/build/ $SSH_SERVER:csdha/public/build/
	rsync -avz -I --delete storage/assets/images/ $SSH_SERVER:csdha/storage/assets/images/
	rsync -avz -I --delete storage/assets/fonts/ $SSH_SERVER:csdha/storage/assets/fonts/
}

rebuild_images() {
	ssh $SSH_SERVER 'cd csdha && bash ./serve -r'
}

while getopts "br" opt; do
	case $opt in
		b) push_assets ;;
		r) rebuild_images ;;
		*) usage ;;
	esac
done

ssh $SSH_SERVER 'cd csdha && bash ./serve'
