#! /bin/sh
# run_serve

usage() {
	echo "Usage: $0 [-br]"
	echo
	exit 1
}

push_assets() {
	npm run build
	rsync -avz -I --delete public/build/ $SSH_SERVER:csdha/public/build/
	rsync -avz -I --delete resources/pdf/images/ $SSH_SERVER:csdha/resources/pdf/images/
	rsync -avz -I --delete resources/pdf/fonts/ $SSH_SERVER:csdha/resources/pdf/fonts/
}

rebuild_images() {
	ssh $SSH_SERVER 'cd csdha && bash ./serve -r'
}

while getopts "br" opt; do
	case $opt in
		b) push_assets ;;
		r) rebuild_images ;;
		*) usage ;;
	esac
done

ssh $SSH_SERVER 'cd csdha && bash ./serve'
