#! /bin/sh
# run_serve

set -e

usage() {
	echo "Usage: $0 [-br]"
	echo
	exit 1
}

push_files() {
	npm run build
	rclone sync resources/pdf/images dropbox:csdha_assets/resources/pdf/images
	rclone sync resources/pdf/fonts dropbox:csdha_assets/resources/pdf/fonts
	rclone sync public/build dropbox:csdha_assets/public/build
	rclone sync public/icon dropbox:csdha_assets/public/icon
	rclone sync public/font dropbox:csdha_assets/public/font
	rclone sync public/images dropbox:csdha_assets/public/images

	rsync -avz k8s/secret.yaml $SSH_SERVER:csdha/k8s/secret.yaml
	rsync -avz .env.production $SSH_SERVER:csdha/.env.production
	rsync -avz .env.production-admin $SSH_SERVER:csdha/.env.production-admin

	rsync -avz k8s/ $SSH_SERVER:csdha/k8s/
	rsync -avz container/ $SSH_SERVER:csdha/container/
}

while getopts "b" opt; do
	case $opt in
		b) push_files ;;
		*) usage ;;
	esac
done

rsync -avz serve $SSH_SERVER:csdha/serve
ssh $SSH_SERVER 'cd csdha && ./serve'

