#! /bin/sh
# serve

export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock
rebuild=0

docker-compose() {
	$HOME/.local/bin/docker-compose $@
}

git pull

usage() {
	echo "Usage: $0 [-r]"
	echo
	exit 1
}

rebuild_images() {
	rebuild=1
	podman compose build
}

while getopts "r" opt; do
	case $opt in
		r) rebuild_images ;;
		*) usage ;;
	esac
done

if [ "$(docker-compose ps -q)" ]; then
	if [ "$rebuild" = "1" ]; then
		rebuild=0
		docker-compose up -d --force-recreate web-user
		docker-compose up -d --force-recreate web-admin
	else
		docker-compose restart web-user
		docker-compose restart web-admin
else
	rebuild=0
	docker-compose up -d
fi

