# web-user.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: csdha-web-user
spec:
  template:
    spec:
      containers:
      - name: web-user
        image: localhost/laravel-web:1.0
        env:
        - name: APP_ENV
          value: production
        volumeMounts:
        - name: web-app 
          mountPath: /var/www/app
        - name: web-app-storage 
          mountPath: /var/www/app/storage
        - name: web-storage 
          mountPath: /var/www/app/storage/app
        - name: web-app-cache 
          mountPath: /var/www/app/bootstrap/cache
      volumes:
      - name: web-storage 
        persistentVolumeClaim:
          claimName: csdha-web-storage
      - name: web-app-storage 
        persistentVolumeClaim:
          claimName: csdha-web-user-storage
      - name: web-app-cache 
        persistentVolumeClaim:
          claimName: csdha-web-user-cache
      - name: web-app 
        persistentVolumeClaim:
          claimName: csdha-web-app

